apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-agri-zvos-app-config
  name: zvos-app-config
  namespace: agri
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-agri-zvos-app-config
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":9890,"dnsName":"zvos-app-config","kind":"ClusterIP","name":"9890tcp2","protocol":"TCP"}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-agri-zvos-app-config
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - zlrancher014
                      - zlrancher012
                      - zlrancher013
                      - zlrancher019
      containers:
      - command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -Dskywalking.trace.ignore_path=/eureka/**
        - -javaagent:/agent/skywalking-agent.jar
        - -jar
        - -Xms256m
        - -Xmx512m
        - /app/zvos-app-config-srv-1.0.0-SNAPSHOT.jar
        - --eureka.client.serviceUrl.defaultZone=http://${EK_URL}:8201/eureka/
        - --eureka.instance.prefer-ip-address=true
        - --spring.datasource.url=${APP_DB_URL}
        - --spring.datasource.username=${APP_DB_USER}
        - --spring.datasource.password=${APP_DB_PASS}
        env:
        - name: SW_AGENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: EK_URL
          valueFrom:
            configMapKeyRef:
              key: eurake-host
              name: host-config
              optional: false
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          valueFrom:
            configMapKeyRef:
              key: backend_service
              name: collector
        - name: APP_DB_URL
          valueFrom:
            configMapKeyRef:
              key: zvos_app_cfg_db
              name: zvos-db-cf
              optional: false
        - name: APP_DB_USER
          valueFrom:
            configMapKeyRef:
              key: zvos_app_cfg_db_user
              name: zvos-db-cf
              optional: false
        - name: APP_DB_PASS
          valueFrom:
            configMapKeyRef:
              key: zvos_app_cfg_db_pass
              name: zvos-db-cf
              optional: false
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
        imagePullPolicy: IfNotPresent
        name: zvos-app-config
        ports:
        - containerPort: 9890
          name: 9890tcp2
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: zvos
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30