stages:
- name: build
  steps:
  - runScriptConfig:
      image: index.paas.zoomlion.com/library/maven-zvos:3.3.9.2
      shellScript: mvn package deploy
- name: 打包
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: zvos/zvos-iot-websocket:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.paas.zoomlion.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
