apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-agri-zvos-mqtt-transport
  name: zvos-mqtt-transport
  namespace: agri
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-agri-zvos-mqtt-transport
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8989,"dnsName":"zvos-mqtt-transport","kind":"ClusterIP","name":"8989tcp2","protocol":"TCP"},{"containerPort":1883,"dnsName":"mqtt-transport-nodeport","kind":"NodePort","name":"1883tcp319001","protocol":"TCP","sourcePort":31900}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-agri-zvos-mqtt-transport
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - zlrancher019
                      - zlrancher012
                      - zlrancher013
                      - zlrancher014
      containers:
      - command:
        - java
        - -jar
        - -Xms256m
        - -Xmx512m
        - /app/zvos-mqtt-transport-srv-1.0.1-SNAPSHOT.jar
        - --eureka.client.serviceUrl.defaultZone=http://${EK_URL}:8201/eureka/
        - --eureka.instance.prefer-ip-address=true
        - --spring.datasource.url=${APP_DB_URL}
        - --spring.cloud.stream.kafka.binder.brokers=${KAFKA_URL}
        - --spring.cloud.stream.kafka.binder.zk-nodes=${ZK_URL}
        env:
        - name: EK_URL
          valueFrom:
            configMapKeyRef:
              key: eurake-host
              name: host-config
              optional: false
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              key: kafka-host
              name: host-config
              optional: false
        - name: ZK_URL
          valueFrom:
            configMapKeyRef:
              key: zk-host
              name: host-config
              optional: false
        - name: SW_AGENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          valueFrom:
            configMapKeyRef:
              key: backend_service
              name: collector
        - name: APP_DB_URL
          valueFrom:
            configMapKeyRef:
              key: zvos_mqtt_db
              name: zvos-db-cf
              optional: false
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
        imagePullPolicy: IfNotPresent
        name: zvos-mqtt-transport
        ports:
        - containerPort: 8989
          name: 8989tcp2
          protocol: TCP
        - containerPort: 1883
          name: 1883tcp319001
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - bd001
        - bd001.hadoop
        ip: 10.224.5.35
      - hostnames:
        - bd002
        - bd002.hadoop
        ip: 10.224.5.220
      - hostnames:
        - bd003
        - bd003.hadoop
        ip: 10.224.4.168
      - hostnames:
        - bd004
        - bd004.hadoop
        ip: 10.224.4.210
      - hostnames:
        - bd005
        - bd005.hadoop
        ip: 10.224.4.8
      - hostnames:
        - bdapp
        - bdapp.hadoop
        ip: 10.224.5.41
      - hostnames:
        - bdwin
        ip: 10.224.4.122
      imagePullSecrets:
      - name: zvos
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
