apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-agri-zvos-iothub-parser
  name: zvos-iothub-parser
  namespace: agri
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-agri-zvos-iothub-parser
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8899,"dnsName":"zvos-iothub-parser","kind":"ClusterIP","name":"8899tcp2","protocol":"TCP"}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-agri-zvos-iothub-parser
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - zlrancher019
                      - zlrancher012
                      - zlrancher013
                      - zlrancher014
      containers:
      - command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - -Xms256m
        - -Xmx512m
        - /app/zvos-iothub-parser-srv-1.0.1-SNAPSHOT.jar
        - --eureka.client.serviceUrl.defaultZone=http://${EK_URL}:8201/eureka/
        - --eureka.instance.prefer-ip-address=true
        - --spring.cloud.stream.binders.kafka1.environment.spring.cloud.stream.kafka.binder.brokers=${KAFKA_URL}
        - --spring.cloud.stream.binders.kafka2.environment.spring.cloud.stream.kafka.binder.brokers=${KAFKA_URL}
        - --spring.cloud.stream.binders.kafka1.environment.spring.cloud.stream.kafka.binder.zk-nodes=${ZK_URL}
        - --spring.cloud.stream.binders.kafka2.environment.spring.cloud.stream.kafka.binder.zk-nodes=${ZK_URL}
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              key: kafka-host
              name: host-config
              optional: false
        - name: ZK_URL
          valueFrom:
            configMapKeyRef:
              key: zk-host
              name: host-config
              optional: false
        - name: EK_URL
          valueFrom:
            configMapKeyRef:
              key: eurake-host
              name: host-config
              optional: false
        - name: SW_AGENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          valueFrom:
            configMapKeyRef:
              key: backend_service
              name: collector
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
        imagePullPolicy: IfNotPresent
        name: zvos-iothub-parser
        ports:
          - containerPort: 8899
            name: 8899tcp2
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /app/wrklib
          name: wrklib
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - bd001
        - bd001.hadoop
        ip: 10.224.5.35
      - hostnames:
        - bd002
        - bd002.hadoop
        ip: 10.224.5.220
      - hostnames:
        - bd003
        - bd003.hadoop
        ip: 10.224.4.168
      - hostnames:
        - bd004
        - bd004.hadoop
        ip: 10.224.4.210
      - hostnames:
        - bd005
        - bd005.hadoop
        ip: 10.224.4.8
      - hostnames:
        - bdapp
        - bdapp.hadoop
        ip: 10.224.5.41
      - hostnames:
        - bdwin
        ip: 10.224.4.122
      imagePullSecrets:
        - name: zvos
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: wrklib
