apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-agri-zvos-iothub-device
  name: zvos-iothub-device
  namespace: agri
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-agri-zvos-iothub-device
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8699,"dnsName":"zvos-iothub-device","kind":"ClusterIP","name":"8699tcp2","protocol":"TCP"}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-agri-zvos-iothub-device
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - zlrancher019
                      - zlrancher012
                      - zlrancher013
                      - zlrancher014
      containers:
      - command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -Dskywalking.trace.ignore_path=/eureka/**
        - -javaagent:/agent/skywalking-agent.jar
        - -jar
        - -Xms256m
        - -Xmx512m
        - /app/zvos-iothub-device-srv-1.0.1-SNAPSHOT.jar
        - --eureka.client.serviceUrl.defaultZone=http://${EK_URL}:8201/eureka/
        - --eureka.instance.prefer-ip-address=true
        - --spring.datasource.url=${APP_DB_URL}
        - --spring.cloud.stream.kafka.binder.brokers=${KAFKA_URL}
        - --spring.cloud.stream.kafka.binder.zk-nodes=${ZK_URL}
        - --spring.redis.host=${REDIS_URL}
        - --device.auth.zl12.ip=10.39.52.226
        - --device.auth.zl12.port=2603
        - --device.auth.zl13.ip=10.39.52.226
        - --device.auth.zl13.port=7055
        - --device.auth.mqtt.ip=222.240.205.186
        - --device.auth.mqtt.port=1883
        - --device.auth.jt808.ip=10.39.52.226
        - --device.auth.jt808.port=6868
        env:
        - name: EK_URL
          valueFrom:
            configMapKeyRef:
              key: eurake-host
              name: host-config
              optional: false
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              key: kafka-host
              name: host-config
              optional: false
        - name: ZK_URL
          valueFrom:
            configMapKeyRef:
              key: zk-host
              name: host-config
              optional: false
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: redis-host
              name: host-config
              optional: false
        - name: SW_AGENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
          valueFrom:
            configMapKeyRef:
              key: backend_service
              name: collector
        - name: APP_DB_URL
          valueFrom:
            configMapKeyRef:
              key: zvos_iothub_device_db
              name: zvos-db-cf
              optional: false
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
        imagePullPolicy: IfNotPresent
        name: zvos-iothub-device
        ports:
        - containerPort: 8699
          name: 8699tcp2
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /home/sysadmin/tmp/download
          name: download
        - mountPath: /home/sysadmin/tmp/upload
          name: upload
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - bd001
        - bd001.hadoop
        ip: 10.224.5.35
      - hostnames:
        - bd002
        - bd002.hadoop
        ip: 10.224.5.220
      - hostnames:
        - bd003
        - bd003.hadoop
        ip: 10.224.4.168
      - hostnames:
        - bd004
        - bd004.hadoop
        ip: 10.224.4.210
      - hostnames:
        - bd005
        - bd005.hadoop
        ip: 10.224.4.8
      - hostnames:
        - bdapp
        - bdapp.hadoop
        ip: 10.224.5.41
      - hostnames:
        - bdwin
        ip: 10.224.4.122
      imagePullSecrets:
      - name: zvos
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: download
      - emptyDir: {}
        name: upload